#!/usr/bin/env perl

use warnings;
use strict;
use Daemon::Control;

use ENV::Util -load_dotenv;

use Cwd qw(abs_path);
use File::Basename;

my $abs_path = abs_path($0);
my $abs_dir  = dirname($0);

my @vars = qw[HOST NAME USER PASS];

if (grep { ! $ENV{"ADSERVER_DB_$_"} } @vars) {
  die "Please define the DB connection variables: ADSERVER_DB*\n";
}

my @program_args;

if ($ENV{ADSERVER_WORKER_COUNT}) {
  push @program_args, '--workers', $ENV{ADSERVER_WORKER_COUNT};
}
if ($ENV{ADSERVER_APP_PORT}) {
  push @program_args, '-l', ":$ENV{ADSERVER_APP_PORT}";
}
if ($ENV{ADSERVER_APP_PRELOAD}) {
  push @program_args, '--preload-app';
}
push @program_args, "$abs_dir/AdServer/bin/app.psgi";

Daemon::Control->new({
  name      => ucfirst lc $ENV{ADSERVER_APP_NAME},
  lsb_start => '$syslog $remote_fs',
  lsb_stop  => '$syslog',
  lsb_sdesc => 'AdServer',
  lsb_desc  => 'AdServer',
  path      => $abs_path,

  program      => '/usr/bin/starman',
  program_args => \@program_args,

  user  => $ENV{ADSERVER_OWNER},
  group => $ENV{ADSERVER_GROUP},

  pid_file    => "/var/run/$ENV{ADSERVER_APP_NAME}.pid",
  stderr_file => "$ENV{ADSERVER_LOG_DIR}/error.log",
  stdout_file => "$ENV{ADSERVER_LOG_DIR}/output.log",

  fork => 2,
})->run;
